# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Build
      run: make build
    - name: Rename file
      run: mv ./out/linux/0gchaind ./out/linux/0gchaind-linux-${{ github.ref_name }}
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: ./out/linux/0gchaind-linux
      env:
        GITHUB_TOKEN: ${{ secrets.WH_UPLOAD_ASSET }}
